### ISSUE TITLE
Remarques concernant le projet original

### ISSUE THREAD

**Issue by brunoilponseisae** [nathanbkm/topoguide-groupe-3#2]
J'ouvre ce ticket pour lister les remarques que j'ai notées sur le projet original de Mathieu:
- Le bouton page précédente à l'air de faire la même chose que le bouton back. Pourquoi cette redondance?
- On aurait aimé un widget adapté à la sélection de la date
- Quand on sauvegarde une sortie, on passe à la visualisation de cette même sortie. On doit repasser par l'acceuil pour retrouver la liste des sorties.
- On aurait aimé que le path '/' donne accès à une vue (liste des itinéraires par exemple)
- l'URL de logout est écrite en dur dans le code et donc ne fonctionne pas sur le serveur d'intégration

**Comment by nathanbkm** [comment]
C'est corrigé
